services:
  open3d-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./input:/source/input
      - ./output:/source/output
    # stdin_open: true
    # tty: true
    # entrypoint: /bin/bash
