services:
  meshroom:
    container_name: meshroom
    image: alicevision/meshroom:2023.3.0-av3.2.0-centos7-cuda11.3.1
    volumes:
      - ./input:/input
      - ./output:/output
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"

  # backend:
  #   build: ./backend
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - redis
  #     - meshroom
  #   volumes:
  #     - ./input:/app/input
  #     - ./output:/app/output
  #   environment:
  #     - REDIS_URL=redis://redis:6379